"""empty message

Revision ID: 19b5f221a030
Revises: 3ed8153a6137
Create Date: 2026-07-11 20:13:39.868299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b5f221a030'
down_revision: Union[str, Sequence[str], None] = '3ed8153a6137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshots', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('snapshots', 'trackable_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'snapshots', 'trackables', ['trackable_id'], ['id'])
    op.add_column('trackables', sa.Column('next_check_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackables', 'next_check_at')
    op.drop_constraint(None, 'snapshots', type_='foreignkey')
    op.alter_column('snapshots', 'trackable_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('snapshots', 'created_at')
    # ### end Alembic commands ###
