"""add instruction and description columns to trackable table

Revision ID: 229b1fbe0288
Revises: 594453a5eb57
Create Date: 2026-07-09 08:20:11.203492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229b1fbe0288'
down_revision: Union[str, Sequence[str], None] = '594453a5eb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('description', sa.String(), nullable=True))
    op.add_column('trackable', sa.Column('instructions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackable', 'instructions')
    op.drop_column('trackable', 'description')
    # ### end Alembic commands ###
