"""Add status table in Trackables

Revision ID: 3075399f272e
Revises: c4ab6e06f17f
Create Date: 2026-07-06 11:48:39.857044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3075399f272e'
down_revision: Union[str, Sequence[str], None] = 'c4ab6e06f17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackable', 'status')
    # ### end Alembic commands ###
