"""Include a last_snapshot column in Trackable table

Revision ID: 3ed8153a6137
Revises: fc13605def0e
Create Date: 2026-07-11 09:33:28.777966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed8153a6137'
down_revision: Union[str, Sequence[str], None] = 'fc13605def0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackables', sa.Column('last_snapshot', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trackables', 'snapshots', ['last_snapshot'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackables', type_='foreignkey')
    op.drop_column('trackables', 'last_snapshot')
    # ### end Alembic commands ###
