"""Add tracked_element_tag column to Tracked

Revision ID: 43d7135e1cad
Revises: f8a80492c792
Create Date: 2026-07-10 10:18:28.428737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d7135e1cad'
down_revision: Union[str, Sequence[str], None] = 'f8a80492c792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('tracked_element_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackable', 'tracked_element_tag')
    # ### end Alembic commands ###
