"""empty message

Revision ID: 51c9c6e3f7d4
Revises: 19b5f221a030
Create Date: 2026-07-11 20:24:02.681725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51c9c6e3f7d4'
down_revision: Union[str, Sequence[str], None] = '19b5f221a030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snapshots', 'trackable_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('snapshots_trackable_id_fkey'), 'snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'snapshots', 'trackables', ['trackable_id'], ['id'], ondelete='CASCADE')
    op.alter_column('trackables', 'next_check_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('trackables_last_snapshot_fkey'), 'trackables', type_='foreignkey')
    op.drop_column('trackables', 'last_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackables', sa.Column('last_snapshot', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('trackables_last_snapshot_fkey'), 'trackables', 'snapshots', ['last_snapshot'], ['id'])
    op.alter_column('trackables', 'next_check_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('snapshots_trackable_id_fkey'), 'snapshots', 'trackables', ['trackable_id'], ['id'])
    op.alter_column('snapshots', 'trackable_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
