"""add trackable_element column to Trackable Table

Revision ID: 653db1355f48
Revises: e27c75751b27
Create Date: 2026-07-10 10:13:48.258807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653db1355f48'
down_revision: Union[str, Sequence[str], None] = 'e27c75751b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('tracked_element', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackable', 'tracked_element')
    # ### end Alembic commands ###
