"""empty message

Revision ID: 6591a497af69
Revises: 51c9c6e3f7d4
Create Date: 2026-07-12 08:06:47.512789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6591a497af69'
down_revision: Union[str, Sequence[str], None] = '51c9c6e3f7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackables', sa.Column('tracked_element_selector', sa.String(), nullable=True))
    op.drop_column('trackables', 'tracked_element_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackables', sa.Column('tracked_element_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trackables', 'tracked_element_selector')
    # ### end Alembic commands ###
