"""add instname column to Trackable table

Revision ID: b9e945397ff1
Revises: 229b1fbe0288
Create Date: 2026-07-09 08:29:56.317713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e945397ff1'
down_revision: Union[str, Sequence[str], None] = '229b1fbe0288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackable', 'name')
    # ### end Alembic commands ###
