"""remove instructions and content type columns from Trackable table

Revision ID: e27c75751b27
Revises: b9e945397ff1
Create Date: 2026-07-09 09:06:15.822721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27c75751b27'
down_revision: Union[str, Sequence[str], None] = 'b9e945397ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackable', 'content_type')
    op.drop_column('trackable', 'instructions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('trackable', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
