"""empty message

Revision ID: e28c59ec053e
Revises: 43d7135e1cad
Create Date: 2026-07-10 10:25:07.418708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28c59ec053e'
down_revision: Union[str, Sequence[str], None] = '43d7135e1cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackable', 'tracked_element_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('tracked_element_tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
