"""Rename tracked_element to tracked_element_class

Revision ID: f8a80492c792
Revises: 653db1355f48
Create Date: 2026-07-10 10:17:31.187879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a80492c792'
down_revision: Union[str, Sequence[str], None] = '653db1355f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('tracked_element_class', sa.String(), nullable=True))
    op.drop_column('trackable', 'tracked_element')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable', sa.Column('tracked_element', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trackable', 'tracked_element_class')
    # ### end Alembic commands ###
